name: 不要创建 Issue，请前往 Disscussions！
description: 不要创建issue
body:
  - type: checkboxes
    attributes:
      label: 不要创建 Issue，请前往 Disscussions
      description: 鉴于大量低质量和重复的issue，从2025年7月开始，用户不可以自行创建issue
      options:
        - label: 我希望这个issue被删除
          required: true
