name: Build Android

on:
  workflow_call:
    inputs:
      app_version_android:
        type: string
        description: The version of the app for Android
        required: true
      task_build_android:
        type: string
        description: The task to run for building the app for Android
        required: false
        default: "tauri:dev:android"
      include_devtools:
        type: boolean
        description: Whether to include devtools in the build
        required: false
        default: false
    secrets:
      TURBO_TOKEN:
        description: Authenticate Turbo to enable Remote Cache
        required: false
      BUILD_ENV:
        description: "Environment variables to pass to `tauri build`. Format: `key1=value1\\nkey2=value2\\n...`"
        required: false

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: "aarch64-linux-android,x86_64-linux-android,armv7-linux-androideabi,i686-linux-android"

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "app/src-tauri -> target"

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Android NDK
        run: sdkmanager "ndk;27.0.11902837"

      - name: Set app version for Android
        run: |
          node ./.github/scripts/set-version.mjs ${{ inputs.app_version_android }}

      - name: Enable DevTools
        if: ${{ inputs.include_devtools }}
        run: |
          node ./.github/scripts/set-tauri-features.mjs devtools
          node ./.github/scripts/enable-sourcemap.mjs

      - name: Write BUILD_ENV to .env file
        run: |
          if [ -n "${{ secrets.BUILD_ENV }}" ]; then
            echo "${{ secrets.BUILD_ENV }}" > app/.env
          fi

      - name: Build Android
        run: |
          pnpm turbo run ${{ inputs.task_build_android }} -- --debug
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/27.0.11902837

      - name: Upload Android APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/src-tauri/gen/android/
