name: Publish Android
run-name: "v${{ inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "应用版本 (x.y.z)"
        required: true
      include_devtools:
        type: boolean
        description: "是否包含开发工具"
        required: false
        default: false

jobs:
  build:
    uses: ./.github/workflows/publish.yml
    with:
      app_version_android: ${{ inputs.version }}
      include_devtools: ${{ inputs.include_devtools }}
      task_build_android: "tauri:build:android"
    secrets:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      BUILD_ENV: |
        LR_API_BASE_URL=${{ secrets.ENV_API_BASE_URL }}
        LR_GITHUB_CLIENT_SECRET=${{ secrets.ENV_GITHUB_CLIENT_SECRET }}
